In [1]:
import numpy as np

In [3]:
base_data=np.arange(100,200)
print('base_data\n={}\n'.format(base_data))


base_data
=[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]



In [4]:
print('base_data[10]={}\n'.format(base_data[10]))

base_data[10]=110



In [6]:
every_five=np.arange(0,100,5)
print(every_five)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
print('base_data(every_five)=\n{}\n'.format(base_data[every_five]))

base_data(every_five)=
[100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]



In [10]:
#array로 인댁싱 할 수 있다
#subscripts

In [11]:
a=np.array([(1,2),(10,20)])
print('a=\n{}\n'.format(a))
print('base_data[a]=\n{}\n'.format(base_data[a]))

a=
[[ 1  2]
 [10 20]]

base_data[a]=
[[101 102]
 [110 120]]



In [13]:
base_data2=base_data.reshape(10,-1)
print('base_data2=np.reshape(base_data,(10,-1))=\n{}\n'.format(base_data2))

base_data2=np.reshape(base_data,(10,-1))=
[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]



In [15]:
print('base_data2[2]=\n{}\n'.format(base_data2[2]))

base_data2[2]=
[120 121 122 123 124 125 126 127 128 129]



In [16]:
print('base_data[2,3]=\n{}\n'.format(base_data2[2,3]))

base_data[2,3]=
123



In [17]:
print('base_data2[-1,-1]=\n{}\n'.format(base_data2[-1,-1]))

base_data2[-1,-1]=
199



In [18]:
print('base_data2[2,:]=\n{}\n'.format(base_data2[2,:]))

base_data2[2,:]=
[120 121 122 123 124 125 126 127 128 129]



In [20]:
print('base_data2[:,3]]=\n{}\n'.format(base_data2[:,3]))

base_data2[:,3]]=
[103 113 123 133 143 153 163 173 183 193]



In [21]:
print('base_data2[2:5,2:4]]=\n{}\n'.format(base_data2[2:5,2:4]))

base_data2[2:5,2:4]]=
[[122 123]
 [132 133]
 [142 143]]



In [22]:
base_data=(np.random.random((5,5))-0.5)*100
print('base_data=\n{}\n'.format(base_data))

base_data=
[[ 28.4879882    9.29098834  -2.37526594 -20.40756477 -30.63033289]
 [ 14.55335503  10.73589282 -18.50044952  43.98138565  21.57986226]
 [-17.21302344  26.40086649  14.96152459  -4.23059214  37.53903832]
 [ 48.15519756 -13.94430999 -19.38208438  39.77865737  40.17819287]
 [-15.5856451   15.59644165  39.30682729  30.53594571  24.55868489]]



In [23]:
print('np.amin(base_data)={}'.format(np.amin(base_data)))

np.amin(base_data)=-30.630332885990086


In [25]:
print('np.amax(base_data)={}'.format(np.amax(base_data)))

np.amax(base_data)=48.15519755751144


In [26]:
print('np.average(base_data)={}'.format(np.average(base_data)))

np.average(base_data)=12.134863233477553


In [28]:
print('np.sum(base_data)={}'.format(np.sum(base_data)))

np.sum(base_data)=303.37158083693885


In [30]:
print('np.sin(base_data)={}'.format(np.sin(base_data)))

np.sin(base_data)=[[-2.12032531e-01  1.33390848e-01 -6.93493458e-01 -9.99918241e-01
   7.07244998e-01]
 [ 9.14636651e-01 -9.66471817e-01  3.42058248e-01 -9.11496963e-04
   3.99788708e-01]
 [ 9.97840157e-01  9.54543727e-01  6.79028663e-01  8.86163750e-01
  -1.59390791e-01]
 [-8.57971512e-01 -9.81460667e-01 -5.07713292e-01  8.73354439e-01
   6.15099085e-01]
 [-1.22013378e-01  1.11290591e-01  9.99318567e-01 -7.70726659e-01
  -5.43042639e-01]]


In [31]:
arr=np.arange(1,20)
arr=arr*arr
print('Multipiles:',arr)


Multipiles: [  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361]


In [32]:
arr=arr-arr
print('-:',arr)


-: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [36]:
arr=np.arange(1,20)
arr=arr+arr
print('+:',arr)


+: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [37]:
arr=np.arange(1,20)
arr=arr/arr
print('Divide:',arr)


Divide: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [38]:
arr=arr+50
print('+50:',arr)

+50: [51. 51. 51. 51. 51. 51. 51. 51. 51. 51. 51. 51. 51. 51. 51. 51. 51. 51.
 51.]
