In [3]:
import numpy as np


In [5]:
zero_line=np.zeros((1,3))
print(zero_line)

[[0. 0. 0.]]


In [7]:
one_column=np.ones((3,1))
print(one_column)

[[1.]
 [1.]
 [1.]]


In [12]:
#.format()#
print('format test {0} {1}'.format('abc','cde'))
print('format test2 {1} {0}'.format('abc','cde'))
print('format test3 {2} {0} {1}'. format('abc','def','ghi'))

format test abc cde
format test2 cde abc
format test3 ghi abc def


In [16]:
print('zero_line=\n{}\n'.format(zero_line))
print('zero_line=\n{}\n'.format(one_column))

zero_line=
[[0. 0. 0.]]

zero_line=
[[1.]
 [1.]
 [1.]]



In [21]:
a=np.array([(1,2,3),(4,5,6)])
b=np.arange(11,20)
print('a= \n{}\n'.format(a))
print('b=\n{}\n'.format(b))

a= 
[[1 2 3]
 [4 5 6]]

b=
[11 12 13 14 15 16 17 18 19]



In [25]:
np.arange(1,2,0.3)

array([1. , 1.3, 1.6, 1.9])

In [27]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [30]:
b=b.reshape(3,-1)
print('b.reshape(3,-1)=\n{}\n'.format(b))


b.reshape(3,-1)=
[[11 12 13]
 [14 15 16]
 [17 18 19]]



In [34]:
#reshape test
test=np.arange(1,17)
test.reshape(4,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
test=np.arange(1,21)
test.reshape(2,10)
test.reshape(4,5)
test.reshape(5,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [42]:
c=np.vstack((a,b,zero_line))
print('c=np.vstack((a,b,zero_line))=\n{}\n'.format(c))

c=np.vstack((a,b,zero_line))=
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]
 [ 0.  0.  0.]]



In [44]:
a=a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
d=np.hstack((a,b,one_column))
print('d=np.hstack((a,b,one_column))=\n{}\n'.format(d))

d=np.hstack((a,b,one_column))=
[[ 1.  2. 11. 12. 13.  1.]
 [ 3.  4. 14. 15. 16.  1.]
 [ 5.  6. 17. 18. 19.  1.]]



In [49]:
e=np.hsplit(d,3)
print(e)
print('e[1]=\n{}\n'.format(e[1]))

[array([[1., 2.],
       [3., 4.],
       [5., 6.]]), array([[11., 12.],
       [14., 15.],
       [17., 18.]]), array([[13.,  1.],
       [16.,  1.],
       [19.,  1.]])]
e[1]=
[[11. 12.]
 [14. 15.]
 [17. 18.]]



In [51]:
f=np.hsplit(d,(1,3))
f


[array([[1.],
        [3.],
        [5.]]), array([[ 2., 11.],
        [ 4., 14.],
        [ 6., 17.]]), array([[12., 13.,  1.],
        [15., 16.,  1.],
        [18., 19.,  1.]])]

In [2]:
g=np.vsplit(d,3)
print(g)

NameError: name 'np' is not defined